### ISSUE TITLE
Don't create "lock files" in the user's project folders

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#26]
The extension creates files named .LCK<filename>~ in my project folders. I don't know the purpose of those lock files, but I doubt VS Code or other tools will recognize/respect those lock files. And if this is solely for the extension's internals, I'd expect it to create those lock files in its own private extension storage somewhere, not in my project folders.

See also https://github.com/apache/netbeans/issues/4962

![image](https://github.com/oracle/javavscode/assets/15714253/7d23a27d-7d61-40a2-bc2a-470ba233877e)

**Comment by limey-git** [comment]
Some`.LCKxxx.java` files were created in a project of mine too.

 I'd moved the real, original `.java` files to a new package but I didn't move the associated NetBeans-generated `.LCKxxx.java` files. 

After that refactor, the orphaned `.LCKxxx.java` files somehow caused the IDE to discard a ton of changes I'd made in the original files before I'd moved them.

I have a hunch that whether or not those files are generated, has _something_ to do with having [_Redhat's/Microsoft's Java extensions_](https:/bit.ly/msftXtnPack) AND this new one from Oracle BOTH enabled.

Most Java devs using vscode would very likely already have the widely-used Java Extension Pack enabled. [_The NetBeans devs_](https:/bit.ly/nbVScode) (@MartinBalin & @ebarboni) [_can't reproduce_](https://github.com/apache/netbeans/issues/4962#issuecomment-1323553063) the `.LCKxxx.java`  behavior , I wonder if the reason they can't MIGHT be because they don't have the [_Java Extension Pack_](https:/bit.ly/msftXtnPack) running. when they try to.

**Comment by anthonyvdotbe** [comment]
> I have a hunch that whether or not those files are generated, has _something_ to do with having [_Redhat's/Microsoft's Java extensions_](https:/bit.ly/msftXtnPack) AND this new one from Oracle BOTH enabled.
> 
> Most Java devs using vscode would very likely already have the widely-used Java Extension Pack enabled. [_The NetBeans devs_](https:/bit.ly/nbVScode) (@MartinBalin & @ebarboni) [_can't reproduce_](https://github.com/apache/netbeans/issues/4962#issuecomment-1323553063) the `.LCKxxx.java` behavior , I wonder if the reason they can't MIGHT be because they don't have the [_Java Extension Pack_](https:/bit.ly/msftXtnPack) running. when they try to.

I'm getting the lock files even with just this extension installed, so other extensions are not the problem. The reason why others are unable to reproduce is simply because there are no clear reproduction steps. For me it happens a lot with Maven `pom.xml` files, but I still have no clue under what conditions those files get created exactly.

**Comment by lahodaj** [comment]
I was trying yesterday, but wasn't able to reproduce yet. I'll try some more.

**Comment by Achal1607** [comment]
Resolved and merged PR

**Comment by anthonyvdotbe** [comment]
@Achal1607 @sid-srini Please reopen this issue. I'm still reproducing with `.java` source files in Maven projects. The linked PR does not resolve the actual issue. The one that does is https://github.com/apache/netbeans/pull/6639 for issue https://github.com/apache/netbeans/issues/4962 and even then the extension will likely have to do something to actually enable the ability.

**Comment by singh-akhilesh** [comment]
> [@Achal1607](https://github.com/Achal1607) [@sid-srini](https://github.com/sid-srini) Please reopen this issue. I'm still reproducing with `.java` source files in Maven projects. The linked PR does not resolve the actual issue. The one that does is [apache/netbeans#6639](https://github.com/apache/netbeans/pull/6639) for issue [apache/netbeans#4962](https://github.com/apache/netbeans/issues/4962) and even then the extension will likely have to do something to actually enable the ability.

Hi @anthonyvdotbe , I tried reproduce the issue with .java source files in Maven Projects (Windows 11 env), but wasn't able to reproduce it. From my testing, the functionality appears to be working as expected. Could you share the exact steps or a sample project where you're still able to reproduce the issue?
<img width="986" height="830" alt="Image" src="https://github.com/user-attachments/assets/b0b3c71a-6ce3-42d8-bf54-e51a5faa8841" />

**Comment by anthonyvdotbe** [comment]
Hi @singh-akhilesh, I have neither exact steps nor a sample project, but I doubt it'll be reproducible with a single hello-world style project. I was working with multiple projects that had a lot of source files with the same package & class name, doing Git rebases where the contents of the projects were changing quickly, etc.

To reproduce, you can investigate under which conditions a [LockForFile](https://github.com/apache/netbeans/blob/master/platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/LockForFile.java) is created and then set up a scenario that triggers it.

Fact is:

* I'm still observing the issue
* the code that creates those lock files is still in NetBeans
* the linked NetBeans PR was not intended to resolve this issue and the PR that *was* never got merged

Will you please reopen? Thanks in advance
